# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iel-bakk <iel-bakk@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/08 01:11:25 by iel-bakk          #+#    #+#              #
#    Updated: 2023/05/20 17:35:41 by iel-bakk         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

CLASS = class/ScalarConverter.hpp

NAME = convert

SRC = src/ScalarConverter.cpp main.cpp
	

OBJ = $(SRC:.cpp=.o)

all : $(NAME)

$(NAME):$(OBJ) $(CLASS)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	rm -f $(OBJ)
fclean: clean
	rm -f $(NAME)
re: fclean all