# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iel-bakk <iel-bakk@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/23 22:23:10 by iel-bakk          #+#    #+#              #
#    Updated: 2023/05/28 22:12:22 by iel-bakk         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

CLASS = class/PmergeMe.hpp

NAME = PmergeMe

SRC = main.cpp src/PmergeMe.cpp
	

OBJ = $(SRC:.cpp=.o)

all : $(NAME)

$(NAME):$(OBJ) $(CLASS)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	rm -f $(OBJ)
fclean: clean
	rm -f $(NAME)
re: fclean all